/* eslint-disable prettier/prettier */

export const highImpactPositiveKeywords = [
  'bullish',
  'partnership',
  'launch',
  'approve',
  'upgrade',
  'record',
  'integrate',
  'surge',
  'acquisition',
  'innovation',
  'expansion',
  'scalability',
  'positive sentiment',
  'token burn',
  'adoption',
  'network effect',
  'uptrend',
  'market share',
  'launchpad',
  'staking rewards',
  'liquidity',
  'governance',
  'tokenization',
  'decentralization',
  'open-source',
  'partnerships with institutions',
  'regulatory clarity',
  'social impact',
  'user growth',
  'green crypto',
  'yield farming',
  'cross-border payments',
  'staking',
  'NFT adoption',
  'blockchain upgrades',
  'liquidity pools',
  'cross-chain interoperability',
  'enterprise adoption',
];

export const highImpactNegativeKeywords = [
  'hack',
  'exploit',
  'sec',
  'regulation',
  'ban',
  'outage',
  'vulnerability',
  'bearish',
  'fine',
  'scam',
  'shutdown',
  'insolvency',
  'price crash',
  'fraud',
  'lawsuit',
  'pump and dump',
  'market manipulation',
  'regulatory crackdown',
  'lawsuit',
  'shutdown',
  'toxic assets',
  'liquidity crisis',
  'recession',
  'bankruptcy',
  'liquidation',
  'bear market',
  'suspension',
  'fud',
  'volatility',
  'whale manipulation',
  'dump',
  'delisting',
  'bank run',
  'overleveraging',
  'underperformance',
  'disruption',
  'exit scam',
  'sudden loss',
  'security breach',
  'insider trading',
  'manipulation',
];

export const macroKeywords = [
  'interest rate',
  'inflation',
  'fed',
  'economy',
  'geopolitical',
  'election',
  'tariff',
  'quantitative easing',
  'global recession',
  'debt crisis',
  'commodity prices',
  'currency devaluation',
  'central bank digital currency (CBDC)',
  'market correction',
  'globalization',
  'economic stimulus',
  'trade war',
  'consumer confidence',
  'central bank policy',
  'unemployment rate',
  'GDP growth',
  'housing market',
  'global trade',
  'digital assets',
  'blockchain adoption',
  'crypto regulation',
  'sovereign debt',
  'monetary policy',
  'global liquidity',
  'stock market',
  'commodity inflation',
  'financial crisis',
  'pandemic impact',
  'tax policy',
  'tech disruption',
  'supply chain',
  'capital flow',
  'monetary tightening',
  'energy crisis',
  'fiscal policy',
  'emerging markets',
  'inflationary pressures',
  'global debt',
];

export interface KeywordFlag {
  keyword: string;
  category: 'positive' | 'negative' | 'macro';
  scoreContribution: number; // The points this specific keyword added
}

export interface EnrichedArticle {
  headline: string;
  summary: string;
  source: string; // Keep the source for context
  flags: KeywordFlag[]; // List of keywords found and their individual score contribution
  initialKeywordScore: number; // Sum of scoreContributions
  overallImportanceScore: number; // The final calculated score from our JS algorithm
}
